In [1]:
import pandas as pd

# Working with json

In [2]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

# Working with sql

In [6]:
!pip install mysql.connector

Collecting mysql.connector

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     -- ------------------------------------- 0.8/11.9 MB 3.0 MB/s eta 0:00:04
     ------ --------------------------------- 1.8/11.9 MB 3.6 MB/s eta 0:00:03
     -------- ------------------------------- 2.6/11.9 MB 3.4 MB/s eta 0:00:03
     ------------ --------------------------- 3.7/11.9 MB 3.7 MB/s eta 0:00:03
     --------------- ------------------------ 4.7/11.9 MB 4.0 MB/s eta 0:00:02
     ------------------- -------------------- 5.8/11.9 MB 4.2 MB/s eta 0:00:02
     ---------------------- ----------------- 6.6/11.9 MB 4.1 MB/s eta 0:00:02
     ------------------------ --------------- 7.3/11.9 MB 4.1 MB/s eta 0:00:02
     --------------------------- ------------ 8.1/11.9 MB 4.1 MB/s eta 0:00:01
     ----------------------------- ---------- 8.7/11.9 MB 4.0 MB/s eta 0:00:01
     ------------------------------- -------- 9.4/11.9 MB 4.0 MB/s eta 0:00:01
     --------------------------------- ------ 10.0/11.9 MB 3.9 MB/s eta 0:00:01
     ----------------------------------- ---- 10.5/11.9 MB 3.8 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 3.7 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 3.6 MB/s  0:00:03
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248051 sha256=b71411cf0c553c865ac04e5615599a0cb52f5fcfddd1ecb32717466955500198
  Stored in directory: c:\users\acer\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [7]:
import mysql.connector

In [10]:
conn = mysql.connector.connect(host="localhost", user="root", password='', database="World")

In [18]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode ='NPL' ", conn)

C:\Users\ACER\AppData\Local\Temp\ipykernel_19024\1591568015.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode ='NPL' ", conn)

     ID        Name CountryCode District  Population
0  2729   Kathmandu         NPL  Central      591835
1  2730  Biratnagar         NPL  Eastern      157764
2  2731     Pokhara         NPL  Western      146318
3  2732   Lalitapur         NPL  Central      145847
4  2733     Birgunj         NPL  Central       90639

In [20]:
df= pd.read_sql_query("SELECT * FROM country",conn)
df

C:\Users\ACER\AppData\Local\Temp\ipykernel_19024\1323132376.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df= pd.read_sql_query("SELECT * FROM country",conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW